name = "d2j"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[triggers]
crons = ["*/15 * * * *"]  # Run every 15 minutes

[build]
command = "npm run build"
watch_dir = "src"

[[d1_databases]]
binding = "DB"
database_name = "d2j"
database_id = "placeholder"  # Will be updated after D1 database creation
